const state = { summary: null, plan: null, crew: 3, spare: false, selected: 'A-104' };
const $ = (s) => document.querySelector(s);
const api = async (url, options = {}) => { const r = await fetch(url, { headers: {'Content-Type':'application/json'}, ...options }); if (!r.ok) throw new Error((await r.json()).detail || 'Request failed'); return r.json(); };
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const color = (risk) => risk > 70 ? 'var(--red)' : risk > 45 ? 'var(--amber)' : 'var(--cyan)';

function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => el.classList.remove('show'), 3500); }
function navigate(view) { document.querySelectorAll('.view').forEach(x => x.classList.toggle('active', x.id === view)); document.querySelectorAll('.nav').forEach(x => x.classList.toggle('active', x.dataset.view === view)); $('#page-title').textContent = ({command:'Fleet Command',health:'Asset Health',planner:'Maintenance Planner',audit:'Decision Audit'})[view]; if (view === 'health') renderHealth(); if (view === 'audit') loadAudit(); window.scrollTo({top:0, behavior:'smooth'}); }
function drawChart(series) { const svg = $('#availability-chart'), w=680,h=220,pad=24; const point = (i,v) => [pad + i*(w-2*pad)/(series.length-1), h-pad-(v-55)*((h-2*pad)/22)]; const path = (key) => series.map((d,i)=>{const [x,y]=point(i,d[key]);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' '); let grids=''; [60,65,70,75].forEach(v=>{const y=point(0,v)[1];grids+=`<line x1="${pad}" y1="${y}" x2="${w-pad}" y2="${y}" stroke="#214053" stroke-width="1"/><text x="2" y="${y+4}" fill="#708899" font-size="10">${v}%</text>`}); const labels=series.map((d,i)=>{const [x]=point(i,0);return `<text x="${x}" y="212" text-anchor="middle" fill="#8199a9" font-size="10">${d.day}</text>`}).join(''); svg.innerHTML=`${grids}<path d="${path('baseline')}" fill="none" stroke="#718797" stroke-width="2" stroke-dasharray="5 4"/><path d="${path('optimized')}" fill="none" stroke="#3ce0d0" stroke-width="3"/>${labels}`; }
function renderCommand() { const s=state.summary; $('#kpis').innerHTML = [ ['FLEET AVAILABILITY',`${s.availability_percent}%`,'Projected today','positive'], ['AT-RISK ASSETS',s.at_risk,'Need planner review','warning'], ['IN MAINTENANCE',s.maintenance,'Active work orders',''], ['DATA FRESHNESS',`${s.data_freshness_seconds}s`,'Telemetry to insight','positive']].map(x=>`<div class="kpi"><small>${x[0]}</small><b class="${x[3]}">${x[1]}</b><span>${x[2]}</span></div>`).join('');
  $('#freshness').textContent = `${s.data_freshness_seconds} seconds ago`; drawChart(s.availability_trend);
  const risky=[...s.assets].sort((a,b)=>b.risk-a.risk).slice(0,3); $('#priority-list').innerHTML=risky.map(a=>`<div class="priority-item"><span class="risk-bar ${a.risk>70?'risk-high':a.risk>45?'risk-medium':'risk-low'}"></span><div><b>${a.id} · ${esc(a.component)}</b><small>${a.rul}h median RUL · ${a.mission} mission priority</small></div><div class="risk-number">${a.risk}%<small>risk</small></div></div>`).join('');
  $('#asset-grid').innerHTML=s.assets.map(a=>`<button class="asset" data-asset="${a.id}" title="View ${a.id} health"><div class="asset-top"><b>${a.id}</b><i class="status-dot" style="background:${color(a.risk)}"></i></div><small>${esc(a.component)}</small><div class="health-meter"><i style="width:${a.health}%;background:${color(a.risk)}"></i></div><small>${a.health}% health score</small></button>`).join(''); document.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.asset;$('#asset-select').value=state.selected;navigate('health')});
}
async function renderHealth() { try { const d=await api(`/api/v1/assets/${state.selected}/health`), a=d.asset; $('#asset-select').innerHTML=state.summary.assets.map(x=>`<option ${x.id===a.id?'selected':''} value="${x.id}">${x.id} · ${x.platform}</option>`).join(''); const max=Math.max(...d.trend.map(t=>t.pressure)); const min=Math.min(...d.trend.map(t=>t.pressure)); const w=680,h=200; const pts=d.trend.map((t,i)=>`${i*(w/(d.trend.length-1))},${h-(t.pressure-min)/(max-min)*160-18}`).join(' '); $('#health-content').innerHTML=`<div class="health-layout"><article class="panel health-card"><div class="panel-head"><div><p class="eyebrow">${a.id} · ${a.platform.toUpperCase()}</p><h2>${esc(a.component)} degradation signal</h2></div><span class="tag ${a.risk>70?'spare-constrained':'scheduled'}">${a.risk}% FAILURE RISK</span></div><div class="chart-wrap"><svg viewBox="0 0 680 200" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#ff6678" stop-opacity=".25"/><stop offset="1" stop-color="#ff6678" stop-opacity="0"/></linearGradient></defs><path d="M0,200 L${pts} L680,200 Z" fill="url(#fill)"/><polyline points="${pts}" fill="none" stroke="#ff7181" stroke-width="3"/></svg></div><p class="muted">Pressure residual is rising across the last 30 flight cycles. Trend has been normalized for operating regime.</p></article><article class="panel health-card"><p class="eyebrow">PROBABILISTIC RUL</p><h2>Remaining useful life</h2><div class="rul-strip"><div class="rul-cell"><small>P10</small><b>${d.rul.p10}h</b></div><div class="rul-cell"><small>P50</small><b>${d.rul.p50}h</b></div><div class="rul-cell"><small>P90</small><b>${d.rul.p90}h</b></div></div><p class="muted">${Math.round(d.rul.confidence*100)}% confidence · maintenance recommendation is inspection before next sortie.</p><div class="model-line"><span>MODEL: ${d.model.version}</span><span>DATA LINEAGE: ${d.model.lineage}</span><span>VALIDATED: ${d.model.last_validated}</span></div></article></div><article class="panel evidence"><div class="panel-head"><div><p class="eyebrow">EXPLAINABLE ALERT</p><h2>Evidence contributing to this prediction</h2></div><span class="muted">Feature attribution snapshot</span></div>${d.evidence.map(e=>`<div class="evidence-row"><span>${e.feature}</span><span class="weight-bar"><i style="width:${e.weight*100}%"></i></span><b>${e.impact}</b></div>`).join('')}</article>`; $('#asset-select').onchange=e=>{state.selected=e.target.value;renderHealth()}; } catch(e){toast(e.message)} }
function renderPlan(plan) { state.plan=plan; $('#approve-button').disabled=false; $('#plan-content').innerHTML=`<div class="plan-summary"><div><small>CURRENT PLAN</small><b>${plan.baseline_availability}%</b><span class="muted">fleet availability</span></div><div><small>AI PLAN</small><b class="positive">${plan.optimized_availability}%</b><span class="muted">fleet availability</span></div><div><small>EXPECTED GAIN</small><b class="positive">+${plan.availability_gain} pts</b><span class="muted">vs current plan</span></div><div><small>PLAN QUALITY</small><b>${plan.objective_score}</b><span class="muted">objective score</span></div></div><table class="plan-table"><thead><tr><th>ASSET / TASK</th><th>RECOMMENDED ACTION</th><th>WINDOW</th><th>RISK / RUL</th><th>SPARES</th><th>STATUS</th></tr></thead><tbody>${plan.actions.map(a=>`<tr><td><b>${a.asset_id}</b><br><span class="muted">${esc(a.component)}</span></td><td><b>${a.action}</b><br><span class="muted">${esc(a.reason)}</span></td><td>${a.start}<br><span class="muted">${a.duration_hours||'—'}h</span></td><td style="color:${color(a.risk)}">${a.risk}%<br><span class="muted">${a.rul_hours}h</span></td><td>${a.spare}</td><td><span class="tag ${a.status.toLowerCase().replace(' ','-')}">${a.status}</span></td></tr>`).join('')}</tbody></table><p class="muted" style="margin-top:13px">Assumptions: ${plan.assumptions.join(' · ')}</p>`; }
async function runPlan(){const btn=$('#run-plan');btn.textContent='Optimizing…';btn.disabled=true;try{renderPlan(await api('/api/v1/optimize/schedule',{method:'POST',body:JSON.stringify({crew_capacity:state.crew,spare_disruption:state.spare})}));toast('AI plan generated with current constraints')}catch(e){toast(e.message)}finally{btn.textContent='Generate AI plan';btn.disabled=false}}
async function loadAudit(){try{const d=await api('/api/v1/audit/events');$('#audit-list').innerHTML=d.events.map(e=>`<div class="audit-event"><time>${e.time}</time><b>${esc(e.actor)}</b><div>${esc(e.event)}<small>${esc(e.detail)}</small></div></div>`).join('')}catch(e){toast(e.message)}}
async function init(){try{state.summary=await api('/api/v1/fleet/summary');renderCommand();}catch(e){toast(`Unable to load console: ${e.message}`)}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>navigate(b.dataset.goto));$('#refresh').onclick=init;$('#audit-refresh').onclick=loadAudit;$('#crew-down').onclick=()=>{state.crew=Math.max(1,state.crew-1);$('#crew-value').textContent=state.crew};$('#crew-up').onclick=()=>{state.crew=Math.min(8,state.crew+1);$('#crew-value').textContent=state.crew};$('#spare-toggle').onchange=e=>state.spare=e.target.checked;$('#run-plan').onclick=runPlan;$('#approve-button').onclick=()=>$('#approval-dialog').showModal();$('#confirm-approval').onclick=async(e)=>{e.preventDefault();const note=$('#approval-note').value.trim();if(note.length<3)return toast('Please add a short decision note');try{const r=await api(`/api/v1/plans/${state.plan.plan_id}/approve`,{method:'POST',body:JSON.stringify({decision:$('#decision').value,note})});$('#approval-dialog').close();$('#approval-note').value='';toast(`Plan ${r.status}; audit event recorded`);loadAudit()}catch(err){toast(err.message)}};init();
